import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navabar/page";
import Login from "./login/page";


const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["300"],
 });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar className="fixed"/> 
        {children}
        </body>
    </html>
  );
}
